### ISSUE TITLE
Flarum admin page doesn't load and also doesn't display any extension I install!

### ISSUE THREAD

**Issue by rubensflinco** [YunoHost-Apps/flarum_ynh#204]
Hello,
I'm opening this problem up for other users to know how to solve it and ask that the people who maintain this repository also solve the problem in the root.

# What's the problem?
Well, the problem I had was the following right after installing the app on my yunohost, I logged in and went to the Flarum admin area, but it didn't load properly and no extension appeared that I installed, it looks like this as in the print:
![](https://i.imgur.com/gUOnsrd.png)

NOTE: it displayed the following error in the browser's console log:
![](https://i.imgur.com/b3Axxbu.png)

Note that the error says that it cannot convert something into JSON, so after downloading the Flarum code to my machine and starting to move around, I found the problem is in a configuration there in the database where there is the "extensions_enabled" that the value it should be an Array but the YunoHost installer creates a broken Array by default, as it comes with a comma at the beginning like this as in the print:
![](https://i.imgur.com/G27qaVZ.png)

# Solution
Well the solution I found to solve here is quite simple, actually.
1 I used PhpMyAdmin installed on my YunoHost to access the Flarum database
2 I went to the "settings" table.
3 I found in the column "key" the value "extensions_enabled"
4 I went to the "value" column of the same line and changed the value of `[,"tituspijean-auth-ldap"]` to `["tituspijean-auth-ldap"]` the database looked like this:
![](https://i.imgur.com/f8x2Pwn.png)

And that's it, I accessed the admin again and that's it, it was right like this:
![](https://i.imgur.com/ZJvIXYX.png)

That's it I hope I helped someone in the future, if I helped you comment here so I know :)

**Comment by tituspijean** [comment]
Hello, and thank you for your extensive investigation, it was on point. :)
I weirdly could not replicate the issue with a new installation nor an upgrade, since the `extensions_enabled` was never empty. But anyways, I took the chance to improve the commands by using `jq` instead of hacking into the string array.

Could you confirm it works on your end, even with an upgrade? `sudo yunohost app upgrade flarum -u https://github.com/YunoHost-Apps/flarum_ynh/tree/fix-ext-enabling -F`
